### ISSUE TITLE
 GAIA object separator

### ISSUE THREAD

**Issue by Hades85** [goto-bus-stop/recanalyst#68]
Fatal error: Uncaught Exception: Could not find GAIA object separator in C:\xampp\htdocs\ageoflan\recanalyst\vendor\recanalyst\recanalyst\src\Analyzers\PlayerObjectsListAnalyzer.php:242 Stack trace: #0 C:\xampp\htdocs\ageoflan\recanalyst\vendor\recanalyst\recanalyst\src\Analyzers\Analyzer.php(40): RecAnalyst\Analyzers\PlayerObjectsListAnalyzer->run() #1 C:\xampp\htdocs\ageoflan\recanalyst\vendor\recanalyst\recanalyst\src\RecordedGame.php(125): RecAnalyst\Analyzers\Analyzer->analyze(Object(RecAnalyst\RecordedGame)) #2 C:\xampp\htdocs\ageoflan\recanalyst\vendor\recanalyst\recanalyst\src\RecordedGame.php(143): RecAnalyst\RecordedGame->runAnalyzer(Object(RecAnalyst\Analyzers\PlayerObjectsListAnalyzer)) #3 C:\xampp\htdocs\ageoflan\recanalyst\vendor\recanalyst\recanalyst\src\Analyzers\Analyzer.php(65): RecAnalyst\RecordedGame->getAnalysis('RecAnalyst\\Anal...', Array, 1573307) #4 C:\xampp\htdocs\ageoflan\recanalyst\vendor\recanalyst\recanalyst\src\Analyzers\PlayerInfoBlockAnalyzer.php(189): RecAnalyst\Analyzers\Analyzer->read(' in C:\xampp\htdocs\ageoflan\recanalyst\vendor\recanalyst\recanalyst\src\Analyzers\PlayerObjectsListAnalyzer.php on line 242

Testfiles can be found here:
https://www.aoezone.net/threads/lan-regicide-between-noobs.150582/

**Comment by phplaw** [comment]
This issue seemed happen on a save & restore game.
