### ISSUE TITLE
analyze not working on v 5.7, v5.8

### ISSUE THREAD

**Issue by tommyg13** [goto-bus-stop/recanalyst#71]
Hello i tried to analyze many games of v5.7 and v5.8 with extension aoe2record but i receive error 500. On the log file i see a warning can't read 4 bytes and it comes from header analyze section. Can someone help me? thanks!

**Comment by goto-bus-stop** [comment]
Could you paste the exact error message here? (and a stack trace if it's there)

Could you upload one of the games here?

I haven't worked with PHP in a while and I don't fully remember what this library supports ATM, but I did learn some more details about the recorded game format since then so I might be able to fix things for 5.8 if necessary.

**Comment by tommyg13** [comment]
Here is the warning i found on logs
mod_fcgid: stderr: PHP Fatal error: Uncaught Exception: Can't read 4 bytes in Analyzer.php:81
mod_fcgid: stderr: #0 MapDataAnalyzer.php(67): RecAnalyst\\Analyzers\\Analyzer->readHeader('l', 4)
mod_fcgid: stderr: #1 MapDataAnalyzer.php(31): RecAnalyst\\Analyzers\\MapDataAnalyzer->skipObstructions()
mod_fcgid: stderr: #2 Analyzer.php(40): RecAnalyst\\Analyzers\\MapDataAnalyzer->run()
mod_fcgid: stderr: #3 RecordedGame.php(125): RecAnalyst\\Analyzers\\Analyzer->analyze(Object(RecAnalyst\\Recorde

[MP Replay v5.7 @2018.06.18 222441 (3).zip](https://github.com/goto-bus-stop/recanalyst/files/3229141/MP.Replay.v5.7.%402018.06.18.222441.3.zip)

**Comment by goto-bus-stop** [comment]
Thanks! there's definitely a bug in the aoe2record header reading code.

**Comment by tommyg13** [comment]
Any idea how to fix it??

**Comment by goto-bus-stop** [comment]
More format research :D I think the Aoe2RecordHeaderAnalyzer.php file in this repository only handles like one or two HD Edition versions so far.

**Comment by tommyg13** [comment]
hello again. i tried to analyze v5.8 and now it works except that the map seems to be broken and the civs images throws 404 error. i noticed that when happen on random civName. I upload two games in case you can take a look and help me fix this issue. Thanks!

[v58.zip](https://github.com/goto-bus-stop/recanalyst/files/3302619/v58.zip)

**Comment by tommyg13** [comment]
hello is there any more updated repo? or someone help me update this?
